### ISSUE TITLE
اصلاح پیشنهاد پروژه

### ISSUE THREAD

**Issue by nournia** [zfallahnejad/Key-Of-The-Sky#1]
دو تا نکته:
- شما در هر فاز باید یک محصول رو ارائه بدید که کار می‌کنه اگرچه ویژگی‌های کمی داشته باشه
- شما باید یک فریم‌ورک رو انتخاب کنید

**Comment by nournia** [comment]
راستی توی ارائه‌تون از تیم هنری صحبت کردید و اینکه فقط در مرحله آخر قرار هست ازش استفاده بشه. امیدوارم معنی‌ش این نباشه که شما به واسط گرافیک کم توجه می‌کنید. چون همونطور که گفتم شما باید در هر فاز محصول **جالبی** رو تحویل بدید

**Comment by jafariali** [comment]
مسائل بیان شده در پروپزال اصلاح شد
